### ISSUE TITLE
Cannot send e-mails with attachments after installing eq_mail_extension

### ISSUE THREAD

**Issue by mcgumbel** [equitania/v11-addons#1]
Hi, thanks a lot for the myodoo port and you valuable apps. :-) However after installing your app "eq_mail_extension" I cannot send any e-mails with attachments. The odoo docker logs shows this error message:

ERROR myodoo11db odoo.addons.eq_mail_extension.models.eq_mail_extension: failed sending mail.mail 8
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/eq_mail_extension/models/eq_mail_extension.py", line 288, in send
    headers=headers)
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_mail_server.py", line 343, in build_email
    for (fname, fcontent, mime) in attachments:
ValueError: not enough values to unpack (expected 3, got 2)

I am using the myodoo 11 docker image. Do you have an idea how to fix this problem?

**Comment by eqms** [comment]
Hi, 
we currently not planning to move to v11. It was only a first test, but there wasn't any effort in v11 for us.
Our modules will tested only on v10.
Maybe you can compare our changes on v10.

**Comment by mcgumbel** [comment]
OK, thank you for the information.
